version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    healthcheck:
      test: "echo 1"
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "5000:5000"
    command: ["sh", "-c", "./wait-for-it.sh mongo:27017 --timeout=0 -- node scripts/createDefaultUser.js && npm start"]
