version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm start
    depends_on:
      - mongo

  electron:
    build:
      context: .
      dockerfile: Dockerfile.electron
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm run electron-start

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
