FROM electronuserland/builder:wine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Set the environment variable to use legacy OpenSSL providers
ENV NODE_OPTIONS=--openssl-legacy-provider

RUN npm run build

CMD ["npm", "run", "electron"]

